name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0
      - name: Install
        run: npm install
      - name: Compile
        run: npx tsc
      - name: Prisma Generate Client
        run: npx prisma generate
      - name: Restart PM2
        run: pm2 start
