name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: latest
      - name: Install
        run: npm install
      - name: Compile
        run: npx tsc
      - name: Prisma Generate Client
        run: npx prisma generate
      - run: npm install pm2@latest -g
      - run: pm2 start

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: executing remote ssh commands using password 4
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}
          key: ${{ secrets.PRIVATE_KEY }}
          command: |
            cd ~/Projects/brubeckAPI
            nvm install --lts
            nvm use --lts
            npm install
            npm install pm2@latest -g
            npx tsc
            npx prisma generate
            pm2 start
