name: Deploy

on:
  push:
    branches:
      - main
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup Node.js environment
  #       uses: actions/setup-node@v3.5.1
  #       with:
  #         node-version: latest
  #     - name: Install
  #       run: npm install
  #     - name: Compile
  #       run: npx tsc
  #     - name: Prisma Generate Client
  #       run: npx prisma generate
  #     - run: npm install pm2@latest -g
  #     - run: pm2 start

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/Projects/brubeckAPI
            git pull
            npm install
            npx prisma generate
            npx tsc
            pm2 start
